### ISSUE TITLE
LIFLayer dynamics

### ISSUE THREAD

**Issue by weinman** [nmi-lab/decolle-public#15]
Thanks to everyone involved for sharing the detailed code and well-written [paper](https://doi.org/10.3389/fnins.2020.00424)  about the method.

I apologize if this is elementary, but I'm trying to reconcile the implementation of the dynamics in `class LIFLayer` with the equations written in the paper.

Specifically, the `forward` method ([here](https://github.com/nmi-lab/decolle-public/blob/8e092e8fe1374aeac59c855a24c383e80db74369/decolle/base_model.py#L229)) updates `Q` and `P` using members `tau_s` and `tau_m`, respectively. 

These members are [set in the constructor](https://github.com/nmi-lab/decolle-public/blob/8e092e8fe1374aeac59c855a24c383e80db74369/decolle/base_model.py#L143); for example (abridged for clarity) 

    tau_m = 1./(1-alpha)

Then `P` is [updated](https://github.com/nmi-lab/decolle-public/blob/8e092e8fe1374aeac59c855a24c383e80db74369/decolle/base_model.py#L235) as

```python
P = self.alpha * state.P + self.tau_m * state.Q  
```
Since the paper defines (Equation 4)

![P_j^l \left[t+\Delta t\right] = \alpha P_j^l\left[t\right] + (1-\alpha) Q_j^l\left[t\right]
](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+P_j%5El+%5Cleft%5Bt%2B%5CDelta+t%5Cright%5D+%3D+%5Calpha+P_j%5El%5Cleft%5Bt%5Cright%5D+%2B+%281-%5Calpha%29+Q_j%5El%5Cleft%5Bt%5Cright%5D%0A)

and 

![\alpha = \exp\left(-\frac{\Delta t}{\tau_{\mathrm{mem}}}\right)](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Calpha+%3D+%5Cexp%5Cleft%28-%5Cfrac%7B%5CDelta+t%7D%7B%5Ctau_%7B%5Cmathrm%7Bmem%7D%7D%7D%5Cright%29),

I'm wondering why the line above isn't

```python
P = self.alpha * state.P + (1-self.alpha) * state.Q  
```

(and perhaps also `tau_m = - dt / log(alpha)`, though I'm not sure this would  matter as much  since `tau_m` seems to have no other use in this class, yet it does in  `class LIFLayerVariableTau`).

Is it simply because 

![\frac{1}{1-\alpha} \approx -\frac{1}{\log \alpha}](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Cfrac%7B1%7D%7B1-%5Calpha%7D+%5Capprox+-%5Cfrac%7B1%7D%7B%5Clog+%5Calpha%7D)

for the range of α values in use?

In sum, what is the reason for using `tau_m` and `tau_s` for updating `P`  and `Q` respectively, rather than `(1-alpha)` and `(1-beta)`?

**Comment by eneftci** [comment]
Thanks for noting this issue. You are correct that there is a mismatch between how the time constants are described in the paper and this repository, due to different versions of the paper. Since we are not training the time constants, this does not affect the overall results. However it does change the interpretation of the parameters.

**Comment by weinman** [comment]
Thanks. I see that 61aca54 fixes the dynamics to match the paper [here](https://github.com/nmi-lab/decolle-public/blob/61aca54dadfc2ef4781a25b8c1324e19f676e871/decolle/base_model.py#L218). Thanks for that! The factorization is much cleaner/clearer (and maybe it's just me, but it also seems to run a bit faster).

I do still wonder a bit about the initialization/definition of `tau_m` (and `tau_s`) [here](https://github.com/nmi-lab/decolle-public/blob/61aca54dadfc2ef4781a25b8c1324e19f676e871/decolle/base_model.py#L93). 

```python
self.tau_m = torch.nn.Parameter(1. / (1 - self.alpha), requires_grad=False)
```

Is this expression simply a convenient, log-avoiding approximation for 

![\alpha = \exp\left(-\frac{\Delta t}{\tau_{\mathrm{mem}}}\right) \Longrightarrow \tau_{\mathrm{mem}} =-\frac{\Delta t}{\log \alpha}](https://render.githubusercontent.com/render/math?math=%5Cdisplaystyle+%5Calpha+%3D+%5Cexp%5Cleft%28-%5Cfrac%7B%5CDelta+t%7D%7B%5Ctau_%7B%5Cmathrm%7Bmem%7D%7D%7D%5Cright%29+%5CLongrightarrow+%5Ctau_%7B%5Cmathrm%7Bmem%7D%7D+%3D-%5Cfrac%7B%5CDelta+t%7D%7B%5Clog+%5Calpha%7D),

or is there something deeper I'm missing?

My thanks again for sharing this work.

**Comment by eneftci** [comment]
The first order approximation is a relic of a previous implementation. The definition with the log you propose is perfectly valid and preferable.
